const money = (v) => (v == null ? null : Number(v));

export const toProductCardDTO = (row) => ({
  id: row.id,
  name: row.name,
  slug: row.slug,
  shortDescription: row.short_description,
  image: row.images?.[0] || null,
  images: row.images,
  price: money(row.price),
  discountPrice: money(row.discount_price),
  currency: row.currency,
  inStock: row.stock > 0,
  location: row.location,
  rating: { avg: row.rating_avg, count: row.rating_count },
  badges: {
    isFeatured: row.is_featured,
    isEditorsPick: row.is_editors_pick,
    isTrending: row.is_trending,
  },
  category: { id: row.category_id, name: row.category_name, slug: row.category_slug },
  artisan: {
    id: row.artisan_id,
    name: row.artisan_name,
    slug: row.artisan_slug,
    verified: row.artisan_verified,
  },
  createdAt: row.created_at,
});

export const toProductDetailDTO = (row) => ({
  id: row.id,
  name: row.name,
  slug: row.slug,
  shortDescription: row.short_description,
  story: row.story,
  craftProcess: row.craft_process,
  materials: row.materials,
  images: row.images,
  price: money(row.price),
  discountPrice: money(row.discount_price),
  currency: row.currency,
  stock: row.stock,
  inStock: row.stock > 0,
  location: row.location,
  rating: { avg: row.rating_avg, count: row.rating_count },
  badges: {
    isFeatured: row.is_featured,
    isEditorsPick: row.is_editors_pick,
    isTrending: row.is_trending,
  },
  category: { id: row.category_id, name: row.category_name, slug: row.category_slug },
  artisan: {
    id: row.artisan_id,
    name: row.artisan_name,
    slug: row.artisan_slug,
    bio: row.artisan_bio,
    story: row.artisan_story,
    avatarUrl: row.artisan_avatar_url,
    location: row.artisan_location,
    craftSpecialty: row.artisan_craft_specialty,
    verified: row.artisan_verified,
    ratingAvg: row.artisan_rating_avg,
  },
  createdAt: row.created_at,
}); 

